

services:
  postgres:
    image: postgres
    container_name: postgresDBgrpc
    environment:
      POSTGRES_USER: valery
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
    driver: local